<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_multi-location-vars-details',
		'title' => 'Multi Location Vars Details',
		'fields' => array (
			array (
				'key' => 'field_59ea09ae8157e',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'instructions' => 'Enter location here',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d1fef0',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'text',
				'instructions' => 'Please add phone number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '15',
			),
            array (
				'key' => 'field_59ea0f6d1fec0',
				'label' => 'Formal Business Name',
				'name' => 'business_name',
				'type' => 'text',
				'instructions' => 'Enter formal business name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d1ferf',
				'label' => 'Address 1',
				'name' => 'address_1',
				'type' => 'text',
				'instructions' => 'Enter your address',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d158hg',
				'label' => 'Address 2',
				'name' => 'address_2',
				'type' => 'text',
				'instructions' => 'Enter your address',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d1fec1',
				'label' => 'City',
				'name' => 'city_1',
				'type' => 'text',
				'instructions' => 'Enter your city',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d1fere',
				'label' => 'State',
				'name' => 'state_1',
				'type' => 'text',
				'instructions' => 'Enter your State	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d1ferg',
				'label' => 'Zip code',
				'name' => 'zip_1',
				'type' => 'text',
				'instructions' => 'Enter your Zip	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
      array (
				'key' => 'field_59ea0f6d1fe4r',
				'label' => 'Facebook URL',
				'name' => 'facebook',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6dksyhr',
				'label' => 'Twitter URL',
				'name' => 'twitter',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d82k5b',
				'label' => 'LinkedIn URL',
				'name' => 'linkedin',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d2s8dff',
				'label' => 'Youtube URL',
				'name' => 'youtube',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_gh29yf6d10pass',
				'label' => 'Pinterest URL',
				'name' => 'pintrest',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6dbass3',
				'label' => 'Instagram URL',
				'name' => 'instagram',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6dbldu',
				'label' => 'Yelp URL',
				'name' => 'yelp',
				'type' => 'text',
				//'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6diwj8e',
				'label' => 'Location Site Name & custom yoast variable value',
				'name' => 'location_custom',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
      ),array (
				'key' => 'field_59ea0f6d2vyjw',
				'label' => "Owner's First Name",
				'name' => 'first_name',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6d8rj3',
				'label' => "Owner's Last Name",
				'name' => 'last_name',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6gewk8',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6jsoth',
				'label' => 'FPC Location Name',
				'name' => 'fpc_location_name',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6jsn46',
				'label' => 'FPC Group',
				'name' => 'fpc_group',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6z54sd',
				'label' => 'FPC Auto Responder ID',
				'name' => 'fpc_responder',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6al98u',
				'label' => 'FPC Account API Key',
				'name' => 'fpc_api_key',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f651g7f',
				'label' => 'Calendar Type',
				'name' => 'calendar_type',
				'type'  => 'radio',
				'choices' => array(
					'google' => esc_html__('Google'),
					'club_ready' => esc_html__('Club Ready'),
					'zen_planner' => esc_html__('Zen Planner'),
					'fitpro_tracker' => esc_html__('Fit Pro Tracker')
				),
				'inline' => false,
			),
			array (
				'key' => 'field_59ea0f6mn67z',
				'label' => 'Fit Pro Tracker URL',
				'name' => 'fit_pro_tracker_url',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6mn89h',
				'label' => 'Calendar API Key',
				'name' => 'cal_api_key',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f63psrw',
				'label' => 'Territory',
				'name' => 'territory',
				'type' => 'text',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ksmdt3der4',
				'label' => 'Google Map URL (only if dynamic map is not working)',
				'name' => 'additional_field',
				'type' => 'text',
				'instructions' => 'Schema Maps are generated dynamically from the street address, but if for some reason the map is not working or incorrect, try inserting the google map url here.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ealaurnd4',
				'label' => 'Latitude',
				'name' => 'additional_field_2',
				'type' => 'text',
				'instructions' => 'For Schema, enter the latitude.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f63sdfder4',
				'label' => 'Longitude',
				'name' => 'additional_field_3',
				'type' => 'text',
				'instructions' => 'For Schema, enter the longitude.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59gfnfgnbh3der4',
				'label' => 'Service Area City 1',
				'name' => 'additional_field_4',
				'type' => 'text',
				'instructions' => 'For schema, enter the primary city the client services.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f63der4',
				'label' => 'Store Hours',
				'name' => 'store_hours',
				'type' => 'textarea',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6xd33e',
				'label' => 'Service Area City 2',
				'name' => 'custom_text_2',
				'type' => 'textarea',
				'instructions' => 'For Schema, enter the 2nd city the client services.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f6514lk',
				'label' => 'Service Area City 3',
				'name' => 'custom_text_3',
				'type' => 'textarea',
				'instructions' => 'For Schema, enter the 3rd city the client services.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59cfbvc0f6olas3',
				'label' => 'Wiki City link',
				'name' => 'custom_text_4',
				'type' => 'textarea',
				'instructions' => 'for Schema, enter the wiki link that corresponds to the primary service area.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59ea0f67toyu',
				'label' => 'Additional text field 5',
				'name' => 'custom_text_5',
				'type' => 'textarea',
			//	'instructions' => 'Enter your custom content	',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
      ),
                    array(
                'key' => 'field_59ea0f68upzv',
                'label' => 'Current Promo',
                'name' => 'current_promo',
                'type' => 'text',
                //	'instructions' => 'Enter your custom content	',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),

            array(
                'key' => 'field_59ea0f68ar12',
                'label' => 'Fit Body Forever AR ID',
                'name' => 'forever_ar_id',
                'type' => 'text',
                //	'instructions' => 'Enter your custom content	',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_59ea0f68Qfb12',
                'label' => 'Multi Location FB',
                'name' => 'multi_location_fb',
                'type' => 'text',
                //	'instructions' => 'Enter your custom content	',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_59ea0f68Ffb12',
                'label' => 'Fbbc FB',
                'name' => 'fbbc_fb',
                'type' => 'text',
                //	'instructions' => 'Enter your custom content	',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_59ea0f68Ffb112',
                'label' => 'Fbbc FB1',
                'name' => 'fbbc_fb1',
                'type' => 'text',
                //	'instructions' => 'Enter your custom content	',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_59ea0f68FBC112',
                'label' => 'Grand Open',
                'name' => 'grandopen',
                'type' => 'text',
                //	'instructions' => 'Enter your custom content	',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
			
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'multi_location_vars',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}



function cptui_register_my_cpts_multi_location_vars() {

	/**
	 * Post Type: Multi Location Vars.
	 */

	$labels = array(
		"name" => __( "QMulti Location Vars", "UnderBoot" ),
		"singular_name" => __( "Variable", "UnderBoot" ),
	);

	$args = array(
		"label" => __( "Multi Location Vars", "UnderBoot" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => false,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => true,
		"exclude_from_search" => true,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "multi_location_vars", "with_front" => false ),
		"query_var" => true,
		"supports" => false,
	);

	register_post_type( "multi_location_vars", $args );
}

add_action( 'init', 'cptui_register_my_cpts_multi_location_vars' );

?>